modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="create_feed_me_packages"
version="${mod_version}"
displayName="Create: Feed Me Packages!"
authors="Scathiard"
description='''
Create logistics delivered straight into a configurable supply-chain cache.
'''

[[mixins]]
config="create_feed_me_packages.mixins.json"

[[dependencies.create_feed_me_packages]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_feed_me_packages]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.create_feed_me_packages]]
modId="create"
type="required"
versionRange="[6.0.10,6.1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_feed_me_packages]]
modId="curios"
type="required"
versionRange="[9.5.1,10.0.0)"
ordering="AFTER"
side="BOTH"
